# Generated by Django 2.0.1 on 2018-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydevice',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, '防火墙'), (1, '入侵检测设备'), (2, '互联网网关'), (3, '运维审计系统')], default=0, verbose_name='服务器类型'),
        ),
    ]
